# Generated by Django 3.0.6 on 2020-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcd',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pcb_id', models.AutoField(primary_key=True, serialize=False)),
                ('pcd_url', models.CharField(max_length=128)),
                ('pcd_name', models.CharField(default='xx.pcd', max_length=128)),
                ('pcd_uuid', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'pcd',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=16, unique=True)),
                ('user_pwd', models.CharField(db_column='user_paw', max_length=100)),
                ('user_tel', models.CharField(db_column='user_tel', max_length=40, unique=True)),
                ('user_idcard', models.CharField(db_column='user_idcard', max_length=80, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
