# Generated by Django 3.0.6 on 2020-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcd',
            name='pcd_uuid',
        ),
        migrations.AlterField(
            model_name='pcd',
            name='pcd_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pcd',
            name='pcd_url',
            field=models.CharField(max_length=64),
        ),
    ]
